### ISSUE TITLE
Calculation of AVG when no change of value

### ISSUE THREAD

**Issue by PeddeF** [iobroker-community-adapters/ioBroker.statistics#109]
**Describe the bug**  
I want to have the average of a value.
Sometimes the value doesn't change within one day.
When the value doesn't change within one day the avg-value is 0

**Expected behavior**  
I want to have the correct avg value.
When the value doesn't change the avg is the same as the value and not 0

**Versions:**  
 - Adapter version: 1.0.10
 - JS-Controller version: 3.3.18
 - Node version: v12.16.3
 - Operating system: linux

**Comment by carhe** [comment]
This issue is related to #102, the observed behavior is another consequence of not considering the timescale.

Configuring the history adapter to store values only on changes means that the samples are not equally spaced (since changes are not equally spaced, in general). I guess that enabling the option to also store unchanged values once in a while could be used as a workaround to solve the problem of getting zeros. However, the nonzero values you get then are still not correct. See #102 for details.

**Comment by PeddeF** [comment]
I'm using influxdb and I changed the configuration of to not only store the changes.
There is no effect und avg-calculation.

The value of temp-avgCount is zero, when there is no change of the value within one day.
So I think, this is more a bug than an enhancement.
